name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build C# Code
      run: dotnet build
        
    - name: run tests
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build

    - name: run tests
      run: dotnet test
    
    - name: Typescript Tests
      working-directory: ./DotnetTemplate.Web
      run: |
        npm t
        npm run lint
    
    - name: Discord Notification
      env: 
        DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The build {{ EVENT_PAYLOAD.repository.full_name }} has been tested.'

    
